// src/lib/schools.ts O'zbekiston maktablari ro'yxati (takrorlanmagan, raqam
// bo'yicha tartiblangan)

export const SCHOOLS : string[] = [
    "1-maktab",
    "2-maktab",
    "3-maktab",
    "4-maktab",
    "5-maktab",
    "6-maktab",
    "7-maktab",
    "8-maktab",
    "9-maktab",
    "10-maktab",
    "11-maktab",
    "12-maktab",
    "13-maktab",
    "14-maktab",
    "15-maktab",
    "16-maktab",
    "17-maktab",
    "18-maktab",
    "19-maktab",
    "20-maktab",
    "21-maktab",
    "22-maktab",
    "23-maktab",
    "24-maktab",
    "25-maktab",
    "26-maktab",
    "27-maktab",
    "28-maktab",
    "29-maktab",
    "30-maktab",
    "31-maktab",
    "32-maktab",
    "33-Maktab",
    "34-Maktab",
    "35-maktab",
    "36-maktab",
    "37-maktab",
    "38-maktab",
    "39-maktab",
    "40-maktab",
    "41-maktab",
    "42-maktab",
    "43-maktab",
    "44-maktab",
    "45-maktab",
    "46-maktab",
    "47-maktab",
    "48-maktab",
    "49-maktab",
    "50-maktab",
    "51-maktab",
    "52-maktab",
    "53-maktab",
    "54-maktab",
    "55-maktab",
    "56-maktab",
    "57-maktab",
    "58-maktab",
    "59-maktab",
    "60-maktab",
    "EdEx xususiy maktabi",
    "Ixtisoslashtirilgan maktab",
    "Progress and Result"
]